In [ ]:
import pandas as pd

In [ ]:
# create a movie Dataset
# Step 1: Create the Movie Dataset
data = {
    'Movie Name': ['Inception', 'Avatar', 'Titanic', 'The Dark Knight', 'Interstellar', 'The Lion King', 'The Avengers', 'Shrek', 'Avengers: Endgame', 'Frozen'],
    'Director': ['Christopher Nolan', 'James Cameron', 'James Cameron', 'Christopher Nolan', 'Christopher Nolan', 'Jon Favreau', 'Joss Whedon', 'Andrew Adamson', 'Anthony Russo, Joe Russo', 'Chris Buck, Jennifer Lee'],
    'Release Year': [2010, 2009, 1997, 2008, 2014, 2019, 2012, 2001, 2019, 2013],
    'Genre': ['Sci-Fi', 'Sci-Fi', 'Romance', 'Action', 'Sci-Fi', 'Animation', 'Action', 'Animation', 'Action', 'Animation'],
    'Rating': [8.8, 7.8, 7.8, 9.0, 8.6, 8.5, 8.0, 7.9, 8.4, 7.5],
    'Budget (in millions)': [160, 237, 200, 185, 165, 260, 220, 60, 356, 150],
    'Box Office Revenue (in millions)': [829, 2790, 2187, 1005, 677, 1650, 1519, 484, 2798, 1270]
}

In [ ]:
# create a dataframe

df = pd.DataFrame(data)

In [ ]:
# display first few rows

df.head()

,Movie Name,Director,Release Year,Genre,Rating,Budget (in millions),Box Office Revenue (in millions)
0,Inception,Christopher Nolan,2010,Sci-Fi,8.8,160,829
1,Avatar,James Cameron,2009,Sci-Fi,7.8,237,2790
2,Titanic,James Cameron,1997,Romance,7.8,200,2187
3,The Dark Knight,Christopher Nolan,2008,Action,9.0,185,1005
4,Interstellar,Christopher Nolan,2014,Sci-Fi,8.6,165,677

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 7 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Movie Name                        10 non-null     object
 1   Director                          10 non-null     object
 2   Release Year                      10 non-null     int64
 3   Genre                             10 non-null     object
 4   Rating                            10 non-null     float64
 5   Budget (in millions)              10 non-null     int64
 6   Box Office Revenue (in millions)  10 non-null     int64
dtypes: float64(1), int64(3), object(3)
memory usage: 692.0+ bytes

In [ ]:
df.describe()

,Release Year,Rating,Budget (in millions),Box Office Revenue (in millions)
count,10.000000,10.000000,10.000000,10.000000
mean,2010.200000,8.230000,199.300000,1520.900000
std,7.036413,0.496767,78.066994,836.468562
min,1997.000000,7.500000,60.000000,484.000000
25%,2008.250000,7.825000,161.250000,873.000000
50%,2011.000000,8.200000,192.500000,1394.500000
75%,2013.750000,8.575000,232.750000,2052.750000
max,2019.000000,9.000000,356.000000,2798.000000

In [ ]:
high_rated_movies = df[df['Rating'] > 8.0]
print(high_rated_movies)

          Movie Name                  Director  Release Year      Genre  \
0          Inception         Christopher Nolan          2010     Sci-Fi
3    The Dark Knight         Christopher Nolan          2008     Action
4       Interstellar         Christopher Nolan          2014     Sci-Fi
5      The Lion King               Jon Favreau          2019  Animation
8  Avengers: Endgame  Anthony Russo, Joe Russo          2019     Action

   Rating  Budget (in millions)  Box Office Revenue (in millions)
0     8.8                   160                               829
3     9.0                   185                              1005
4     8.6                   165                               677
5     8.5                   260                              1650
8     8.4                   356                              2798

In [ ]:
sorted_by_year = df.sort_values(by = 'Release Year', ascending = False)
print(sorted_by_year)

          Movie Name                  Director  Release Year      Genre  \
8  Avengers: Endgame  Anthony Russo, Joe Russo          2019     Action
5      The Lion King               Jon Favreau          2019  Animation
4       Interstellar         Christopher Nolan          2014     Sci-Fi
9             Frozen  Chris Buck, Jennifer Lee          2013  Animation
6       The Avengers               Joss Whedon          2012     Action
0          Inception         Christopher Nolan          2010     Sci-Fi
1             Avatar             James Cameron          2009     Sci-Fi
3    The Dark Knight         Christopher Nolan          2008     Action
7              Shrek            Andrew Adamson          2001  Animation
2            Titanic             James Cameron          1997    Romance

   Rating  Budget (in millions)  Box Office Revenue (in millions)
8     8.4                   356                              2798
5     8.5                   260                              1650
4     8.6                   165                               677
9     7.5                   150                              1270
6     8.0                   220                              1519
0     8.8                   160                               829
1     7.8                   237                              2790
3     9.0                   185                              1005
7     7.9                    60                               484
2     7.8                   200                              2187

In [ ]:
high_revenue_movies = df[df['Box Office Revenue (in millions)'] > 500]
print(high_revenue_movies)

          Movie Name                  Director  Release Year      Genre  \
0          Inception         Christopher Nolan          2010     Sci-Fi
1             Avatar             James Cameron          2009     Sci-Fi
2            Titanic             James Cameron          1997    Romance
3    The Dark Knight         Christopher Nolan          2008     Action
4       Interstellar         Christopher Nolan          2014     Sci-Fi
5      The Lion King               Jon Favreau          2019  Animation
6       The Avengers               Joss Whedon          2012     Action
8  Avengers: Endgame  Anthony Russo, Joe Russo          2019     Action
9             Frozen  Chris Buck, Jennifer Lee          2013  Animation

   Rating  Budget (in millions)  Box Office Revenue (in millions)
0     8.8                   160                               829
1     7.8                   237                              2790
2     7.8                   200                              2187
3     9.0                   185                              1005
4     8.6                   165                               677
5     8.5                   260                              1650
6     8.0                   220                              1519
8     8.4                   356                              2798
9     7.5                   150                              1270

In [ ]:
sorted_by_rev_value = df.sort_values(by = 'Box Office Revenue (in millions)', ascending = False)
print(sorted_by_rev_value)

          Movie Name                  Director  Release Year      Genre  \
8  Avengers: Endgame  Anthony Russo, Joe Russo          2019     Action
1             Avatar             James Cameron          2009     Sci-Fi
2            Titanic             James Cameron          1997    Romance
5      The Lion King               Jon Favreau          2019  Animation
6       The Avengers               Joss Whedon          2012     Action
9             Frozen  Chris Buck, Jennifer Lee          2013  Animation
3    The Dark Knight         Christopher Nolan          2008     Action
0          Inception         Christopher Nolan          2010     Sci-Fi
4       Interstellar         Christopher Nolan          2014     Sci-Fi
7              Shrek            Andrew Adamson          2001  Animation

   Rating  Budget (in millions)  Box Office Revenue (in millions)
8     8.4                   356                              2798
1     7.8                   237                              2790
2     7.8                   200                              2187
5     8.5                   260                              1650
6     8.0                   220                              1519
9     7.5                   150                              1270
3     9.0                   185                              1005
0     8.8                   160                               829
4     8.6                   165                               677
7     7.9                    60                               484

In [ ]:
average_rating = df['Rating'].mean()
print(average_rating)

8.23

In [ ]:
total_budget = df['Budget (in millions)'].sum()
print(total_budget)

1993

In [ ]:
highest_grossing_movie = df.sort_values(by = 'Box Office Revenue (in millions)', ascending = False).iloc[0]
print(highest_grossing_movie)

Movie Name                                 Avengers: Endgame
Director                            Anthony Russo, Joe Russo
Release Year                                            2019
Genre                                                 Action
Rating                                                   8.4
Budget (in millions)                                     356
Box Office Revenue (in millions)                        2798
Name: 8, dtype: object

In [ ]:
# grouping

avg_rating_by_genre = df.groupby('Genre')['Rating'].mean()
print(avg_rating_by_genre)

Genre
Action       8.466667
Animation    7.966667
Romance      7.800000
Sci-Fi       8.400000
Name: Rating, dtype: float64

In [ ]:
tot_revenue_by_director = df.groupby('Director')['Box Office Revenue (in millions)'].sum()
print(tot_revenue_by_director)

Director
Andrew Adamson               484
Anthony Russo, Joe Russo    2798
Chris Buck, Jennifer Lee    1270
Christopher Nolan           2511
James Cameron               4977
Jon Favreau                 1650
Joss Whedon                 1519
Name: Box Office Revenue (in millions), dtype: int64

In [ ]:
# calculate profits

df['Profit (in millions)'] = df['Box Office Revenue (in millions)'] - df['Budget (in millions)']
print("Dataset with Profit column:")
print(df[["Movie Name", "Profit (in millions)"]], "\n")


highest_profit_movie = df.loc[df['Profit (in millions)'].idxmax()]
print(highest_profit_movie)

Dataset with Profit column:
          Movie Name  Profit (in millions)
0          Inception                   669
1             Avatar                  2553
2            Titanic                  1987
3    The Dark Knight                   820
4       Interstellar                   512
5      The Lion King                  1390
6       The Avengers                  1299
7              Shrek                   424
8  Avengers: Endgame                  2442
9             Frozen                  1120

Movie Name                                 Avatar
Director                            James Cameron
Release Year                                 2009
Genre                                      Sci-Fi
Rating                                        7.8
Budget (in millions)                          237
Box Office Revenue (in millions)             2790
Profit (in millions)                         2553
Name: 1, dtype: object